// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveData;

namespace SaveData.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("FileManager.FilesData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ArchBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ArchFiles")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AudioBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AudioFiles")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DocumentBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DocumentFiles")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Files")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("FilmBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("FilmFiles")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ImageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ImageFiles")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RestBytes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RestFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("FilesData");
                });

            modelBuilder.Entity("SaveData.DataSet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataSetDrivesID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DataID");

                    b.HasIndex("DataSetDrivesID");

                    b.ToTable("SavedDataFiles");
                });

            modelBuilder.Entity("SaveData.DataSetDrives", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("SavedDataDrives");
                });

            modelBuilder.Entity("SaveData.DataSet", b =>
                {
                    b.HasOne("FileManager.FilesData", "Data")
                        .WithMany()
                        .HasForeignKey("DataID");

                    b.HasOne("SaveData.DataSetDrives", null)
                        .WithMany("Data")
                        .HasForeignKey("DataSetDrivesID");
                });
#pragma warning restore 612, 618
        }
    }
}
